spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  application:
    name: xasync-demo

logging:
  level:
    root: debug

x-async:
  #使用内存保存任务
  strategy-memory:
    #开关，默认值：true
    enable: true
    config:
      #异步任务执行线程池核心线程数，有默认值
      core-pool-size: 3
      #最大执行次数，有默认值
      max-execute-count: 3
      #异步重试间隔，单位毫秒，有默认值
      period-ms: 1000
      #异步任务提交后延迟执行时间，单位毫秒，有默认值
      initial_delay_ms: 100
  #使用rocketmq保存任务
  strategy-rocketmq:
    #开关，默认开启
    enable: false
    config:
      #保存任务的主题,有默认值
      topic: x-async-task-test0
      #消息的tag，有默认值
      tag: all
      #消费者组，有默认值
      consumer-group: ${spring.application.name}

#以下为rocketMq原生配置，x-async.strategy-rocketmq.enable:true 时添加
#rocketmq:
#  name-server: 192.168.99.88:9876;192.168.99.74:9876
#  #生产者
#  producer:
#    #生产者组名，规定在一个应用里面必须唯一
#    group: ${spring.application.name}
#    #消息发送的超时时间 默认3000ms
#    send-message-timeout: 3000
#    #消息达到4096字节的时候，消息就会被压缩。默认 4096
#    compress-message-body-threshold: 4096
#    #最大的消息限制，默认为128K
#    max-message-size: 4194304
#    #同步消息发送失败重试次数
#    retry-times-when-send-failed: 3
#    #在内部发送失败时是否重试其他代理，这个参数在有多个broker时才生效
#    retry-next-server: true
#    #异步消息发送失败重试的次数
#    retry-times-when-send-async-failed: 3